Dennish02/UPTask

backend/.gitignore
Arreglo bug para tapar los ".env"
=> fix .env in .gitignore

backend/controladores/nftController.js, backend/index.js, backend/middleware/idGenerator.js, backend/models/nft.js, frontend/src/Assets/build/css/app.css, frontend/src/Assets/scss/base/_mixins.scss, frontend/src/Assets/scss/layout/_index.scss, frontend/src/Assets/scss/layout/_main.scss, frontend/src/Assets/scss/layout/_nftTarget.scss, frontend/src/componentes/home/ComponentNFT.jsx, frontend/src/pages/Home.jsx
Esta hecha la targeta del nft, y se actualizo la parte del back del modelo para que traiga bien el id,embien estilos
=> actualizacion

server/index.js
=> Create new Branch

frontend/package-lock.json, frontend/package.json, frontend/src/Assets/build/css/app.css, frontend/src/Assets/scss/layout/_index.scss, frontend/src/Assets/scss/layout/_profileModal.scss, frontend/src/componentes/home/NavBar.jsx, frontend/src/componentes/modalProfile/profileSettings.jsx
=> modal profile

server/connection.js, server/models/user.js, server/package.json, server/routes/nft.js, server/routes/routes.js, server/routes/user.js, server/routes/wallet.js
Conecte rutas a archivo conecction, cree archivos de rutas en routes, mando modelo basico de usuario y rutas de prueba. Lo probe con usuarios y llega a Mongo
=> Conexion rutas, modelo y rutas usuario basico

server/models/user.js, server/package.json
Agregue la condicion unique a nombre de usuario, y el pre save para encriptar la contraseña (ambos en archivo modelo de usuario). Tambien agregue al package el bcrypt
=> Se agrego condicion unique a nombre de usuario, y el pre save que enc

backend/controladores/nftController.js, backend/controladores/usuarioController.js, backend/models/Usuarios.js
Ahora al crear un NFT se guarda en la propiedad nfts del modelo Usuario y se puede acceder a los datos de cada usuario desde la ruta usuarios/perfil con su respectivo token
=> Ruta GET PERFIL y propiedad NFTs en MODELO USUARIO

backend/models/transaccion.js
Modelo de transaccion. Como los NFTs se van a poder comprar, regalar o intercambiar, creo que se tiene que especificar en la transaccion.
=> modelo de transaccion

backend/models/coleccion.js, backend/models/nft.js
Modelos de categoria y coleccion. Tambien se modificó el archivo del modelo de nft
=> modelos de categoria y coleccion

backend/models/Usuarios.js
Solo agregue el virtual en modelo de usuario y saque el atributo nfts. Al hacer usuario.nfts nos traeria todos los nfts que le pertenece. Y al hacer transacciones y cambiar el owner se mantendria actualizado.
=> Virtual de Nfts en modelo de usuario

backend/controladores/nftController.js
solucioné el error de traer todos los nfts de un usuario
=> Fix "allNftUser" route bug

backend/controladores/nftController.js, backend/controladores/usuarioController.js, backend/routes/nftRoutes.js, frontend/.gitignore
Hice la ruta para regalar nfts y agregué un par de cositas al gitingore del front para que no se suba el package-lock.json
=> fix some gitignore errors - feature gift nft route

frontend/redux/actions/actionNFT.js, frontend/redux/constantes/index.js, frontend/redux/reducers/index.js, frontend/src/componentes/home/SearchBar.jsx
ahora deberia estar todo bien odio git
=> aber ahora G

backend/controladores/nftController.js, backend/routes/nftRoutes.js
ruta para comprar y poner en venta nfts. Se arreglo el filtrado de nft por _id
=> Compra venta nfts back

backend/controladores/transaccionesController.js, backend/index.js, backend/models/Usuarios.js, backend/models/transaccion.js, backend/routes/transaccionesRoutes.js
=> Ruta ventas de usuario

backend/controladores/nftController.js
agregué varios condicionales para cuando se crea un nft
=> Fix "crearNft" bugs

frontend/src/pages/Register.jsx
agregue un boton para q el usuario pueda logearse en /register en el caso de que haya tocado get started y ya tenga una cuenta
=> boton agregado

frontend/redux/actions/actionNFT.js, frontend/src/componentes/portfolio/UserNFT.jsx
edit nft ahora esta full validado en el front no tiene bugs
=> Arreglar bugs

frontend/src/Assets/scss/base/_mixins.scss, frontend/src/Assets/scss/layout/_nftTarget.scss, frontend/src/Assets/scss/layout/_resetPassword.scss, frontend/src/componentes/portfolio/UserNFT.jsx, frontend/src/pages/Portfolio.jsx
=> estilos-editar-precio

backend/controladores/nftController.js, frontend/redux/reducers/index.js, frontend/src/Assets/scss/base/_mixins.scss, frontend/src/Assets/scss/layout/_navbar.scss, frontend/src/componentes/home/ComponentNFT.jsx, frontend/src/componentes/home/NavBar.jsx, frontend/src/componentes/home/SearchBar.jsx, frontend/src/pages/Home.jsx
arreglo en busqueda y filtrado de nfts a la venta
=> arreglo en busqueda y filtrado de nfts a la venta

frontend/src/App.jsx, frontend/src/Assets/build/css/app.css, frontend/src/Assets/scss/layout/_index.scss, frontend/src/Assets/scss/layout/_wallet.scss, frontend/src/componentes/portfolio/UserNFT.jsx, frontend/src/componentes/wallet/ComponentNFTWallet.jsx, frontend/src/componentes/wallet/NavWallet.jsx, frontend/src/pages/Wallet.jsx
Creacion de page wallet, y sus componentes Navbarwallet y componentNftWallet
=> Wallet actualizada
